# from Card import *
from cardsInfo import *
from allCards import *

#
# Mostly Not in Use. Only category lists are being used for backtracking algorithm
#

# Cards separated by win condition, air troops, ground cards, and spell cards
winCards = {
    "Hog Rider",
    "Goblin Giant",
    "Ram Rider",
    "Skeleton Barrel",
    "Battle Ram",
    "Goblin Barrel",
    "Electro Giant",
    "Graveyard",
    "Royal Giant",
    "X-Bow",
    "Balloon",
    "Sparky",
    "Three Musketeers",
    "Giant",
    "Golem",
    "Goblin Drill",
    "Elixir Golem",
    "Mega Knight",
    "Lava Hound",
    "P.E.K.K.A",
    "Royal Hogs",
    "Mortar",
    "Miner",
    "Wall Breakers",
}

airCards = {
    "Fire Spirit",
    "Spear Goblins",
    "Bats",
    "Archers",
    "Minions",
    "Goblin Gang",
    "Firecracker",
    "Skeleton Dragons",
    "Tesla",
    "Minion Horde",
    "Mega Minion",
    "Rascals",
    "Dart Goblin",
    "Musketeer",
    "Flying Machine",
    "Zappies",
    "Wizard",
    "Inferno Tower",
    "Three Musketeers",
    "Baby Dragon",
    "Witch",
    "Hunter",
    "Executioner",
    "Princess",
    "Ice Wizard",
    "Magic Archer",
    "Inferno Dragon",
    "Electro Wizrd",
    "Night Witch",
    "Archer Queen",
    "Balloon",
    "Fireball",
    "Tordado",
    "Rocket",
    "Snowball",
    "Arrows",
    "Zap",
}

groundCards = {
    "Bandit",
    "Giant Skeleton",
    "Bomber",
    "Barbarians",
    "Ice Golem",
    "Valkyrie",
    "Bomb Tower",
    "Goblins",
    "Mini P.E.K.K.A",
    "Cannon",
    "Skeleton Army",
    "Fisherman",
    "Royal Ghost",
    "Battle Healer",
    "Barbarian Hut",
    "Skeletons",
    "Tombstone",
    "Bowler",
    "Dark Prince",
    "Cannon Cart",
    "Rascals",
    "Goblin Gang",
    "Lumberjack",
    "Prince",
    "Royal Recruits",
    "Guards",
    "Knight",
    "Night Witch",
    "Elite Barbarians",
}

spellCards = {
    "Earthquake",
    "Zap",
    "Arrows",
    "Royal Delivery",
    "Rage",
    "Barbarian Barrel",
    "Fireball",
    "Clone",
    "Freeze",
    "The Log",
    "Rocket",
    "Poison",
    "Mirror",
    "Lightning",
    "Tornado",
    "Giant Snowball",
}
