# Compiled using data from clash royale API https://developer.clashroyale.com/#/
cardsInfo = {
    "Knight": {
        "key": "knight",
        "name": "Knight",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Common",
        "arena": 0,
        "description": "A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone.",
        "id": 26000000,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
    },
    "Archers": {
        "key": "archers",
        "name": "Archers",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Common",
        "arena": 0,
        "description": "A pair of lightly armored ranged attackers. They'll help you take down ground and air units, but you're on your own with hair coloring advice.",
        "id": 26000001,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/W4Hmp8MTSdXANN8KdblbtHwtsbt0o749BbxNqmJYfA8.png",
    },
    "Goblins": {
        "key": "goblins",
        "name": "Goblins",
        "elixir": 2,
        "type": "Troop",
        "rarity": "Common",
        "arena": 1,
        "description": "Three fast, unarmored melee attackers. Small, fast, green and mean!",
        "id": 26000002,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/X_DQUye_OaS3QN6VC9CPw05Fit7wvSm3XegXIXKP--0.png",
    },
    "Giant": {
        "key": "giant",
        "name": "Giant",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 0,
        "description": "Slow but durable, only attacks buildings. A real one-man wrecking crew!",
        "id": 26000003,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Axr4ox5_b7edmLsoHxBX3vmgijAIibuF6RImTbqLlXE.png",
    },
    "P.E.K.K.A": {
        "key": "pekka",
        "name": "P.E.K.K.A",
        "elixir": 7,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 4,
        "description": "A heavily armored, slow melee fighter. Swings from the hip, but packs a huge punch.",
        "id": 26000004,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/MlArURKhn_zWAZY-Xj1qIRKLVKquarG25BXDjUQajNs.png",
    },
    "Minions": {
        "key": "minions",
        "name": "Minions",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Common",
        "arena": 0,
        "description": "Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!",
        "id": 26000005,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/yHGpoEnmUWPGV_hBbhn-Kk-Bs838OjGzWzJJlQpQKQA.png",
    },
    "Balloon": {
        "key": "balloon",
        "name": "Balloon",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 2,
        "description": "As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage.",
        "id": 26000006,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png",
    },
    "Witch": {
        "key": "witch",
        "name": "Witch",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 0,
        "description": "Summons Skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers.",
        "id": 26000007,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/cfwk1vzehVyHC-uloEIH6NOI0hOdofCutR5PyhIgO6w.png",
    },
    "Barbarians": {
        "key": "barbarians",
        "name": "Barbarians",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Common",
        "arena": 3,
        "description": "A horde of melee attackers with mean mustaches and even meaner tempers.",
        "id": 26000008,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/TvJsuu2S4yhyk1jVYUAQwdKOnW4U77KuWWOTPOWnwfI.png",
    },
    "Golem": {
        "key": "golem",
        "name": "Golem",
        "elixir": 8,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 3,
        "description": "Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!",
        "id": 26000009,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/npdmCnET7jmVjJvjJQkFnNSNnDxYHDBigbvIAloFMds.png",
    },
    "Skeletons": {
        "key": "skeletons",
        "name": "Skeletons",
        "elixir": 1,
        "type": "Troop",
        "rarity": "Common",
        "arena": 2,
        "description": "Three fast, very weak melee fighters. Surround your enemies with this pile of bones!",
        "id": 26000010,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/oO7iKMU5m0cdxhYPZA3nWQiAUh2yoGgdThLWB1rVSec.png",
    },
    "Valkyrie": {
        "key": "valkyrie",
        "name": "Valkyrie",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 2,
        "description": "Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins.",
        "id": 26000011,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
    },
    "Skeleton Army": {
        "key": "skeleton-army",
        "name": "Skeleton Army",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 0,
        "description": "Spawns an army of Skeletons. Meet Larry and his friends Harry, Gerry, Terry, Mary, etc.",
        "id": 26000012,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/fAOToOi1pRy7svN2xQS6mDkhQw2pj9m_17FauaNqyl4.png",
    },
    "Bomber": {
        "key": "bomber",
        "name": "Bomber",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Common",
        "arena": 2,
        "description": "Small, lightly protected skeleton that throws bombs. Deals area damage that can wipe out a swarm of enemies.",
        "id": 26000013,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/12n1CesxKIcqVYntjxcF36EFA-ONw7Z-DoL0_rQrbdo.png",
    },
    "Musketeer": {
        "key": "musketeer",
        "name": "Musketeer",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 0,
        "description": "Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick.",
        "id": 26000014,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
    },
    "Baby Dragon": {
        "key": "baby-dragon",
        "name": "Baby Dragon",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 0,
        "description": "Burps fireballs from the sky that deal area damage. Baby dragons hatch cute, hungry and ready for a barbeque.",
        "id": 26000015,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/cjC9n4AvEZJ3urkVh-rwBkJ-aRSsydIMqSAV48hAih0.png",
    },
    "Prince": {
        "key": "prince",
        "name": "Prince",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 0,
        "description": "Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Deals double damage once he gets charging.",
        "id": 26000016,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/3JntJV62aY0G1Qh6LIs-ek-0ayeYFY3VItpG7cb9I60.png",
    },
    "Wizard": {
        "key": "wizard",
        "name": "Wizard",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 5,
        "description": "The most awesome man to ever set foot in the Arena, the Wizard will blow you away with his handsomeness... and/or fireballs.",
        "id": 26000017,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
    },
    "Mini P.E.K.K.A": {
        "key": "mini-pekka",
        "name": "Mini P.E.K.K.A",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 0,
        "description": "The Arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction.",
        "id": 26000018,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Fmltc4j3Ve9vO_xhHHPEO3PRP3SmU2oKp2zkZQHRZT4.png",
    },
    "Spear Goblins": {
        "key": "spear-goblins",
        "name": "Spear Goblins",
        "elixir": 2,
        "type": "Troop",
        "rarity": "Common",
        "arena": 1,
        "description": "Three unarmored ranged attackers. Who the heck taught these guys to throw spears!? Who thought that was a good idea?!",
        "id": 26000019,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/FSDFotjaXidI4ku_WFpVCTWS1hKGnFh1sxX0lxM43_E.png",
    },
    "Giant Skeleton": {
        "key": "giant-skeleton",
        "name": "Giant Skeleton",
        "elixir": 6,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 2,
        "description": "The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies.",
        "id": 26000020,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/0p0gd0XaVRu1Hb1iSG1hTYbz2AN6aEiZnhaAib5O8Z8.png",
    },
    "Hog Rider": {
        "key": "hog-rider",
        "name": "Hog Rider",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 1,
        "description": 'Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of "Hog Riderrrrr" all the way through the Arena doors.',
        "id": 26000021,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Ubu0oUl8tZkusnkZf8Xv9Vno5IO29Y-jbZ4fhoNJ5oc.png",
    },
    "Minion Horde": {
        "key": "minion-horde",
        "name": "Minion Horde",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Common",
        "arena": 4,
        "description": "Six fast, unarmored flying attackers. Three's a crowd, six is a horde!",
        "id": 26000022,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Wyjq5l0IXHTkX9Rmpap6HaH08MvjbxFp1xBO9a47YSI.png",
    },
    "Ice Wizard": {
        "key": "ice-wizard",
        "name": "Ice Wizard",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 8,
        "description": "This chill caster throws ice shards that slow down enemies' movement and attack speed. Despite being freezing cold, he has a handlebar mustache that's too hot for TV.",
        "id": 26000023,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/W3dkw0HTw9n1jB-zbknY2w3wHuyuLxSRIAV5fUT1SEY.png",
    },
    "Royal Giant": {
        "key": "royal-giant",
        "name": "Royal Giant",
        "elixir": 6,
        "type": "Troop",
        "rarity": "Common",
        "arena": 7,
        "description": "Destroying enemy buildings with his massive cannon is his job; making a raggedy blond beard look good is his passion.",
        "id": 26000024,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/mnlRaNtmfpQx2e6mp70sLd0ND-pKPF70Cf87_agEKg4.png",
    },
    "Guards": {
        "key": "guards",
        "name": "Guards",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 7,
        "description": "Three ruthless bone brothers with shields. Knock off their shields and all that's left are three ruthless bone brothers.",
        "id": 26000025,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/1ArKfLJxYo6_NU_S9cAeIrfbXqWH0oULVJXedxBXQlU.png",
    },
    "Princess": {
        "key": "princess",
        "name": "Princess",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 7,
        "description": "This stunning Princess shoots flaming arrows from long range. If you're feeling warm feelings towards her, it's probably because you're on fire.",
        "id": 26000026,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/bAwMcqp9EKVIKH3ZLm_m0MqZFSG72zG-vKxpx8aKoVs.png",
    },
    "Dark Prince": {
        "key": "dark-prince",
        "name": "Dark Prince",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 7,
        "description": "The Dark Prince deals area damage and lets his spiked club do the talking for him - because when he does talk, it sounds like he has a bucket on his head.",
        "id": 26000027,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/M7fXlrKXHu2IvpSGpk36kXVstslbR08Bbxcy0jQcln8.png",
    },
    "Three Musketeers": {
        "key": "three-musketeers",
        "name": "Three Musketeers",
        "elixir": 9,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 7,
        "description": "Trio of powerful, independent markswomen, fighting for justice and honor. Disrespecting them would not be just a mistake, it would be a cardinal sin!",
        "id": 26000028,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/_J2GhbkX3vswaFk1wG-dopwiHyNc_YiPhwroiKF3Mek.png",
    },
    "Lava Hound": {
        "key": "lava-hound",
        "name": "Lava Hound",
        "elixir": 7,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 4,
        "description": "The Lava Hound is a majestic flying beast that attacks buildings. The Lava Pups are less majestic angry babies that attack anything.",
        "id": 26000029,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/unicRQ975sBY2oLtfgZbAI56ZvaWz7azj-vXTLxc0r8.png",
    },
    "Ice Spirit": {
        "key": "ice-spirit",
        "name": "Ice Spirit",
        "elixir": 1,
        "type": "Troop",
        "rarity": "Common",
        "arena": 8,
        "description": "Spawns one lively little Ice Spirit to freeze a group of enemies. Stay frosty.",
        "id": 26000030,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/lv1budiafU9XmSdrDkk0NYyqASAFYyZ06CPysXKZXlA.png",
    },
    "Fire Spirit": {
        "name": "Fire Spirit",
        "elixir": 1,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/16-BqusVvynIgYI8_Jci3LDC-r8AI_xaIYLgXqtlmS8.png",
    },
    "Miner": {
        "key": "miner",
        "name": "Miner",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 4,
        "description": "The Miner can burrow his way underground and appear anywhere in the Arena. It's not magic, it's a shovel.",
        "id": 26000032,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Y4yWvdwBCg2FpAZgs8T09Gy34WOwpLZW-ttL52Ae8NE.png",
    },
    "Sparky": {
        "key": "sparky",
        "name": "Sparky",
        "elixir": 6,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 11,
        "description": "Sparky slowly charges up, then unloads MASSIVE area damage. Overkill isn't in her vocabulary.",
        "id": 26000033,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/2GKMkBrArZXgQxf2ygFjDs4VvGYPbx8F6Lj_68iVhIM.png",
    },
    "Bowler": {
        "key": "bowler",
        "name": "Bowler",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 8,
        "description": "This big blue dude digs the simple things in life - Dark Elixir drinks and throwing rocks. His massive boulders roll through their target, hitting everything behind for a strike!",
        "id": 26000034,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/SU4qFXmbQXWjvASxVI6z9IJuTYolx4A0MKK90sTIE88.png",
    },
    "Lumberjack": {
        "key": "lumberjack",
        "name": "Lumberjack",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 8,
        "description": "He chops trees by day and hunts The Log by night. His bottle of Rage spills everywhere when he dies.",
        "id": 26000035,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/E6RWrnCuk13xMX5OE1EQtLEKTZQV6B78d00y8PlXt6Q.png",
    },
    "Battle Ram": {
        "key": "battle-ram",
        "name": "Battle Ram",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 3,
        "description": "Two Barbarians holding a big log charge at the nearest building, dealing significant damage if they connect; then they go to town with their swords!",
        "id": 26000036,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/dyc50V2cplKi4H7pq1B3I36pl_sEH5DQrNHboS_dbbM.png",
    },
    "Inferno Dragon": {
        "key": "inferno-dragon",
        "name": "Inferno Dragon",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 6,
        "description": "Shoots a focused beam of fire that increases in damage over time. Wears a helmet because flying can be dangerous.",
        "id": 26000037,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/y5HDbKtTbWG6En6TGWU0xoVIGs1-iQpIP4HC-VM7u8A.png",
    },
    "Ice Golem": {
        "key": "ice-golem",
        "name": "Ice Golem",
        "elixir": 2,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 8,
        "description": "He's tough, targets buildings and explodes when destroyed, slowing nearby enemies. Made entirely out of ice... or is he?! Yes.",
        "id": 26000038,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png",
    },
    "Mega Minion": {
        "key": "mega-minion",
        "name": "Mega Minion",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 4,
        "description": "Flying, armored and powerful. What could be its weakness?! Cupcakes.",
        "id": 26000039,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/-T_e4YLbuhPBKbYnBwQfXgynNpp5eOIN_0RracYwL9c.png",
    },
    "Dart Goblin": {
        "key": "dart-goblin",
        "name": "Dart Goblin",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 9,
        "description": "Runs fast, shoots far and chews gum. How does he blow darts with a mouthful of Double Trouble Gum? Years of didgeridoo lessons.",
        "id": 26000040,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/BmpK3bqEAviflqHCdxxnfm-_l3pRPJw3qxHkwS55nCY.png",
    },
    "Goblin Gang": {
        "key": "goblin-gang",
        "name": "Goblin Gang",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Common",
        "arena": 9,
        "description": "Spawns five Goblins - three with knives, two with spears - at a discounted Elixir cost. It's like a Goblin Value Pack!",
        "id": 26000041,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/NHflxzVAQT4oAz7eDfdueqpictb5vrWezn1nuqFhE4w.png",
    },
    "Electro Wizard": {
        "key": "electro-wizard",
        "name": "Electro Wizard",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 11,
        "description": 'He lands with a "POW!", stuns nearby enemies and shoots lightning with both hands! What a show off.',
        "id": 26000042,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/RsFaHgB3w6vXsTjXdPr3x8l_GbV9TbOUCvIx07prbrQ.png",
    },
    "Elite Barbarians": {
        "key": "elite-barbarians",
        "name": "Elite Barbarians",
        "elixir": 6,
        "type": "Troop",
        "rarity": "Common",
        "arena": 10,
        "description": "Spawns a pair of leveled up Barbarians. They're like regular Barbarians, only harder, better, faster and stronger.",
        "id": 26000043,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/C88C5JH_F3lLZj6K-tLcMo5DPjrFmvzIb1R2M6xCfTE.png",
    },
    "Hunter": {
        "key": "hunter",
        "name": "Hunter",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 1,
        "description": "He deals BIG damage up close - not so much at range. What he lacks in accuracy, he makes up for with his impressively bushy eyebrows.",
        "id": 26000044,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/VNabB1WKnYtYRSG7X_FZfnZjQDHTBs9A96OGMFmecrA.png",
    },
    "Executioner": {
        "key": "executioner",
        "name": "Executioner",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 9,
        "description": "He throws his axe like a boomerang, striking all enemies on the way out AND back. It's a miracle he doesn't lose an arm.",
        "id": 26000045,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/9XL5BP2mqzV8kza6KF8rOxrpCZTyuGLp2l413DTjEoM.png",
    },
    "Bandit": {
        "key": "bandit",
        "name": "Bandit",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 9,
        "description": "The Bandit dashes to her target and delivers an extra big hit! While dashing, she can't be touched. The mask keeps her identity safe, and gives her bonus cool points!",
        "id": 26000046,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/QWDdXMKJNpv0go-HYaWQWP6p8uIOHjqn-zX7G0p3DyM.png",
    },
    "Royal Recruits": {
        "key": "royal-recruits",
        "name": "Royal Recruits",
        "elixir": 8,
        "type": "Troop",
        "rarity": "Common",
        "arena": 7,
        "description": "Deploys a line of recruits armed with spears, shields and wooden buckets. They dream of ponies and one day wearing metal buckets.",
        "id": 26000047,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/jcNyYGUiXXNz3kuz8NBkHNKNREQKraXlb_Ts7rhCIdM.png",
    },
    "Night Witch": {
        "key": "night-witch",
        "name": "Night Witch",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 5,
        "description": "Summons Bats to do her bidding, even after death! If you get too close, she isn't afraid of pitching in with her mean-looking battle staff.",
        "id": 26000048,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/NpCrXDEDBBJgNv9QrBAcJmmMFbS7pe3KCY8xJ5VB18A.png",
    },
    "Bats": {
        "key": "bats",
        "name": "Bats",
        "elixir": 2,
        "type": "Troop",
        "rarity": "Common",
        "arena": 5,
        "description": "Spawns a handful of tiny flying creatures. Think of them as sweet, purple... balls of DESTRUCTION!",
        "id": 26000049,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/EnIcvO21hxiNpoI-zO6MDjLmzwPbq8Z4JPo2OKoVUjU.png",
    },
    "Royal Ghost": {
        "key": "royal-ghost",
        "name": "Royal Ghost",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 7,
        "description": "He drifts invisibly through the Arena until he's startled by an enemy... then he attacks! Then he's invisible again! Zzzz.",
        "id": 26000050,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/3En2cz0ISQAaMTHY3hj3rTveFN2kJYq-H4VxvdJNvCM.png",
    },
    "Ram Rider": {
        "name": "Ram Rider",
        "elixir": 5,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/QaJyerT7f7oMyZ3Fv1glKymtLSvx7YUXisAulxl7zRI.png",
    },
    "Zappies": {
        "key": "zappies",
        "name": "Zappies",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 11,
        "description": "Spawns a pack of miniature Zap machines. Who controls them...? Only the Master Builder knows.",
        "id": 26000052,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/QZfHRpLRmutZbCr5fpLnTpIp89vLI6NrAwzGZ8tHEc4.png",
    },
    "Rascals": {
        "key": "rascals",
        "name": "Rascals",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Common",
        "arena": 9,
        "description": "Spawns a mischievous trio of Rascals! The boy takes the lead, while the girls pelt enemies from behind... with slingshots full of Double Trouble Gum!",
        "id": 26000053,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/KV48DfwVHKx9XCjzBdk3daT_Eb52Me4VgjVO7WctRc4.png",
    },
    "Cannon Cart": {
        "key": "cannon-cart",
        "name": "Cannon Cart",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 6,
        "description": "A Cannon on wheels?! Bet they won't see that coming! Once you break its shield, it becomes a Cannon not on wheels.",
        "id": 26000054,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/aqwxRz8HXzqlMCO4WMXNA1txynjXTsLinknqsgZLbok.png",
    },
    "Mega Knight": {
        "key": "mega-knight",
        "name": "Mega Knight",
        "elixir": 7,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 10,
        "description": "He lands with the force of 1,000 mustaches, then jumps from one foe to the next dealing huge area damage. Stand aside!",
        "id": 26000055,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/O2NycChSNhn_UK9nqBXUhhC_lILkiANzPuJjtjoz0CE.png",
    },
    "Skeleton Barrel": {
        "key": "skeleton-barrel",
        "name": "Skeleton Barrel",
        "elixir": 3,
        "type": "Troop",
        "rarity": "Common",
        "arena": 6,
        "description": "It's a Skeleton party in the sky, until all the balloons pop... then it's a Skeleton party on the ground!",
        "id": 26000056,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/vCB4DWCcrGbTkarjcOiVz4aNDx6GWLm0yUepg9E1MGo.png",
    },
    "Flying Machine": {
        "key": "flying-machine",
        "name": "Flying Machine",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 6,
        "description": "The Master Builder has sent his first contraption to the Arena! It's a fast and fun flying machine, but fragile!",
        "id": 26000057,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/hzKNE3QwFcrSrDDRuVW3QY_OnrDPijSiIp-PsWgFevE.png",
    },
    "Wall Breakers": {
        "name": "Wall Breakers",
        "elixir": 2,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/_xPphEfC8eEwFNrfU3cMQG9-f5JaLQ31ARCA7l3XtW4.png",
    },
    "Royal Hogs": {
        "key": "royal-hogs",
        "name": "Royal Hogs",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Rare",
        "arena": 10,
        "description": "The King's personal pets are loose! They love to chomp on apples and towers alike - who let the hogs out?!",
        "id": 26000059,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/ASSQJG_MoVq9e81HZzo4bynMnyLNpNJMfSLb3hqydOw.png",
    },
    "Goblin Giant": {
        "key": "goblin-giant",
        "name": "Goblin Giant",
        "elixir": 6,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 9,
        "description": "This jolly green Goblin Giant stomps towards enemy buildings. He carries two Spear Goblins everywhere he goes. It's a weird but functional arrangement.",
        "id": 26000060,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/SoW16cY3jXBwaTDvb39DkqiVsoFVaDWbzf5QBYphJrY.png",
    },
    "Fisherman": {
        "name": "Fisherman",
        "alert": "NO INFO FROM ROAYLE API",
        "elixir": 3,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/U2KZ3g0wyufcuA5P2Xrn3Z3lr1WiJmc5S0IWOZHgizQ.png",
    },
    "Magic Archer": {
        "key": "magic-archer",
        "name": "Magic Archer",
        "elixir": 4,
        "type": "Troop",
        "rarity": "Legendary",
        "arena": 10,
        "description": "Not quite a Wizard, nor an Archer - he shoots a magic arrow that passes through and damages all enemies in its path. It's not a trick, it's magic!",
        "id": 26000062,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Avli3W7BxU9HQ2SoLiXnBgGx25FoNXUSFm7OcAk68ek.png",
    },
    "Electro Dragon": {
        "key": "electro-dragon",
        "name": "Electro Dragon",
        "elixir": 5,
        "type": "Troop",
        "rarity": "Epic",
        "arena": 11,
        "description": "Spits out bolts of electricity hitting up to three targets. Suffers from middle child syndrome to boot.",
        "id": 26000063,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/tN9h6lnMNPCNsx0LMFmvpHgznbDZ1fBRkx-C7UfNmfY.png",
    },
    "Firecracker": {
        "name": "Firecracker",
        "alert": "NO INFO FROM ROAYLE API",
        "elixir": 3,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/c1rL3LO1U2D9-TkeFfAC18gP3AO8ztSwrcHMZplwL2Q.png",
    },
    "Elixir Golem": {
        "name": "Elixir Golem",
        "elixir": 3,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/puhMsZjCIqy21HW3hYxjrk_xt8NIPyFqjRy-BeLKZwo.png",
    },
    "Battle Healer": {
        "name": "Battle Healer",
        "elixir": 3,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/KdwXcoigS2Kg-cgA7BJJIANbUJG6SNgjetRQ-MegZ08.png",
    },
    "Skeleton King": {
        "name": "Skeleton King",
        "elixir": 4,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/dCd69_wN9f8DxwuqOGtR4QgWhHIPIaTNxZ1e23RzAAc.png",
    },
    "Archer Queen": {
        "name": "Archer Queen",
        "elixir": 5,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/p7OQmOAFTery7zCzlpDdm-LOD1kINTm42AwIHchZfWk.png",
    },
    "Golden Knight": {
        "name": "Golden Knight",
        "elixir": 4,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/WJd207D0O1sN-l1FTb8P9KhYL2oF5jY26vRUfTUW3FQ.png",
    },
    "Skeleton Dragons": {
        "name": "Skeleton Dragons",
        "elixir": 4,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/qPOtg9uONh47_NLxGhhFc_ww9PlZ6z3Ry507q1NZUXs.png",
    },
    "Mother Witch": {
        "name": "Mother Witch",
        "elixir": 4,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/fO-Xah8XZkYKaSK9SCp3wnzwxtvIhun9NVY-zzte1Ng.png",
    },
    "Electro Spirit": {
        "name": "Electro Spirit",
        "elixir": 1,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/WKd4-IAFsgPpMo7dDi9sujmYjRhOMEWiE07OUJpvD9g.png",
    },
    "Electro Giant": {
        "name": "Electro Giant",
        "elixir": 8,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/_uChZkNHAMq6tPb3v6A49xinOe3CnhjstOhG6OZbPYc.png",
    },
    "Cannon": {
        "key": "cannon",
        "name": "Cannon",
        "elixir": 3,
        "type": "Building",
        "rarity": "Common",
        "arena": 3,
        "description": "Defensive building. Shoots cannonballs with deadly effect, but cannot target flying troops.",
        "id": 27000000,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/nZK1y-beLxO5vnlyUhK6-2zH2NzXJwqykcosqQ1cmZ8.png",
    },
    "Goblin Hut": {
        "key": "goblin-hut",
        "name": "Goblin Hut",
        "elixir": 5,
        "type": "Building",
        "rarity": "Rare",
        "arena": 1,
        "description": "Building that spawns Spear Goblins. Don't look inside... you don't want to see how they're made.",
        "id": 27000001,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/l8ZdzzNLcwB4u7ihGgxNFQOjCT_njFuAhZr7D6PRF7E.png",
    },
    "Mortar": {
        "key": "mortar",
        "name": "Mortar",
        "elixir": 4,
        "type": "Building",
        "rarity": "Common",
        "arena": 6,
        "description": "Defensive building with a long range. Shoots big boulders that deal area damage, but cannot hit targets that get too close!",
        "id": 27000002,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/lPOSw6H7YOHq2miSCrf7ZDL3ANjhJdPPDYOTujdNrVE.png",
    },
    "Inferno Tower": {
        "key": "inferno-tower",
        "name": "Inferno Tower",
        "elixir": 5,
        "type": "Building",
        "rarity": "Rare",
        "arena": 4,
        "description": "Defensive building, roasts targets for damage that increases over time. Burns through even the biggest and toughest enemies!",
        "id": 27000003,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/GSHY_wrooMMLET6bG_WJB8redtwx66c4i80ipi4gYOM.png",
    },
    "Bomb Tower": {
        "key": "bomb-tower",
        "name": "Bomb Tower",
        "elixir": 4,
        "type": "Building",
        "rarity": "Rare",
        "arena": 10,
        "description": "Defensive building that houses a Bomber. Deals area damage to anything dumb enough to stand near it.",
        "id": 27000004,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/rirYRyHPc97emRjoH-c1O8uZCBzPVnToaGuNGusF3TQ.png",
    },
    "Barbarian Hut": {
        "key": "barbarian-hut",
        "name": "Barbarian Hut",
        "elixir": 7,
        "type": "Building",
        "rarity": "Rare",
        "arena": 3,
        "description": "Building that periodically spawns Barbarians to fight the enemy. Time to make the Barbarians!",
        "id": 27000005,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/ho0nOG2y3Ch86elHHcocQs8Fv_QNe0cFJ2CijsxABZA.png",
    },
    "Tesla": {
        "key": "tesla",
        "name": "Tesla",
        "elixir": 4,
        "type": "Building",
        "rarity": "Common",
        "arena": 11,
        "description": "Defensive building. Whenever it's not zapping the enemy, the power of Electrickery is best kept grounded.",
        "id": 27000006,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/OiwnGrxFMNiHetYEerE-UZt0L_uYNzFY7qV_CA_OxR4.png",
    },
    "Elixir Collector": {
        "key": "elixir-collector",
        "name": "Elixir Collector",
        "elixir": 6,
        "type": "Building",
        "rarity": "Rare",
        "arena": 8,
        "description": "You gotta spend Elixir to make Elixir.",
        "id": 27000007,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/BGLo3Grsp81c72EpxLLk-Sofk3VY56zahnUNOv3JcT0.png",
    },
    "X-Bow": {
        "key": "x-bow",
        "name": "X-Bow",
        "elixir": 6,
        "type": "Building",
        "rarity": "Epic",
        "arena": 6,
        "description": "Nice tower you got there. Would be a shame if this X-Bow whittled it down from this side of the Arena...",
        "id": 27000008,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/zVQ9Hme1hlj9Dc6e1ORl9xWwglcSrP7ejow5mAhLUJc.png",
    },
    "Tombstone": {
        "key": "tombstone",
        "name": "Tombstone",
        "elixir": 3,
        "type": "Building",
        "rarity": "Rare",
        "arena": 2,
        "description": "Troop building that periodically deploys Skeletons to fight the enemy. When destroyed, spawns 4 Skeletons. Creepy!",
        "id": 27000009,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/LjSfSbwQfkZuRJY4pVxKspZ-a0iM5KAhU8w-a_N5Z7Y.png",
    },
    "Furnace": {
        "key": "furnace",
        "name": "Furnace",
        "elixir": 4,
        "type": "Building",
        "rarity": "Rare",
        "arena": 5,
        "description": "The Furnace spawns two Fire Spirits at a time. It also makes great brick-oven pancakes.",
        "id": 27000010,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/iqbDiG7yYRIzvCPXdt9zPb3IvMt7F7Gi4wIPnh2x4aI.png",
    },
    "Goblin Cage": {
        "name": "Goblin Cage",
        "alert": "NO INFO FROM ROAYLE API",
        "elixir": 4,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/vD24bBgK4rSq7wx5QEbuqChtPMRFviL_ep76GwQw1yA.png",
    },
    "Goblin Drill": {
        "name": "Goblin Drill",
        "elixir": 4,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/eN2TKUYbih-26yBi0xy5LVFOA0zDftgDqxxnVfdIg1o.png",
    },
    "Fireball": {
        "key": "fireball",
        "name": "Fireball",
        "elixir": 4,
        "type": "Spell",
        "rarity": "Rare",
        "arena": 0,
        "description": "Annnnnd... Fireball. Incinerates a small area, dealing high damage. Reduced damage to Crown Towers.",
        "id": 28000000,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/lZD9MILQv7O-P3XBr_xOLS5idwuz3_7Ws9G60U36yhc.png",
    },
    "Arrows": {
        "key": "arrows",
        "name": "Arrows",
        "elixir": 3,
        "type": "Spell",
        "rarity": "Common",
        "arena": 0,
        "description": "Arrows pepper a large area, damaging all enemies hit. Reduced damage to Crown Towers.",
        "id": 28000001,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Flsoci-Y6y8ZFVi5uRFTmgkPnCmMyMVrU7YmmuPvSBo.png",
    },
    "Rage": {
        "key": "rage",
        "name": "Rage",
        "elixir": 2,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 10,
        "description": "Increases troop movement and attack speed. Buildings attack faster and summon troops quicker, too. Chaaaarge!",
        "id": 28000002,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/bGP21OOmcpHMJ5ZA79bHVV2D-NzPtDkvBskCNJb7pg0.png",
    },
    "Rocket": {
        "key": "rocket",
        "name": "Rocket",
        "elixir": 6,
        "type": "Spell",
        "rarity": "Rare",
        "arena": 6,
        "description": "Deals high damage to a small area. Looks really awesome doing it. Reduced damage to Crown Towers.",
        "id": 28000003,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Ie07nQNK9CjhKOa4-arFAewi4EroqaA-86Xo7r5tx94.png",
    },
    "Goblin Barrel": {
        "key": "goblin-barrel",
        "name": "Goblin Barrel",
        "elixir": 3,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 1,
        "description": "Spawns three Goblins anywhere in the Arena. It's going to be a thrilling ride, boys!",
        "id": 28000004,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/CoZdp5PpsTH858l212lAMeJxVJ0zxv9V-f5xC8Bvj5g.png",
    },
    "Freeze": {
        "key": "freeze",
        "name": "Freeze",
        "elixir": 4,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 5,
        "description": "Freezes troops and buildings, making them unable to move or attack. Everybody chill.",
        "id": 28000005,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/I1M20_Zs_p_BS1NaNIVQjuMJkYI_1-ePtwYZahn0JXQ.png",
    },
    "Mirror": {
        "key": "mirror",
        "name": "Mirror",
        "elixir": 1,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 11,
        "description": "Mirrors your last card played for +1 Elixir.",
        "id": 28000006,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/wC6Cm9rKLEOk72zTsukVwxewKIoO4ZcMJun54zCPWvA.png",
    },
    "Lightning": {
        "key": "lightning",
        "name": "Lightning",
        "elixir": 6,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 4,
        "description": "Bolts of lightning damage and stun up to three enemy troops or buildings with the most hitpoints in the target area. Reduced damage to Crown Towers.",
        "id": 28000007,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/fpnESbYqe5GyZmaVVYe-SEu7tE0Kxh_HZyVigzvLjks.png",
    },
    "Zap": {
        "key": "zap",
        "name": "Zap",
        "elixir": 2,
        "type": "Spell",
        "rarity": "Common",
        "arena": 4,
        "description": "Zaps enemies, briefly stunning them and dealing damage inside a small radius. Reduced damage to Crown Towers.",
        "id": 28000008,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/7dxh2-yCBy1x44GrBaL29vjqnEEeJXHEAlsi5g6D1eY.png",
    },
    "Poison": {
        "key": "poison",
        "name": "Poison",
        "elixir": 4,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 5,
        "description": "Covers the area in a deadly toxin, damaging enemy troops and buildings over time. Yet somehow leaves the grass green and healthy. Go figure!",
        "id": 28000009,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/98HDkG2189yOULcVG9jz2QbJKtfuhH21DIrIjkOjxI8.png",
    },
    "Graveyard": {
        "key": "graveyard",
        "name": "Graveyard",
        "elixir": 5,
        "type": "Spell",
        "rarity": "Legendary",
        "arena": 5,
        "description": "Surprise! It's a party. A Skeleton party, anywhere in the Arena. Yay!",
        "id": 28000010,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Icp8BIyyfBTj1ncCJS7mb82SY7TPV-MAE-J2L2R48DI.png",
    },
    "The Log": {
        "key": "the-log",
        "name": "The Log",
        "elixir": 2,
        "type": "Spell",
        "rarity": "Legendary",
        "arena": 6,
        "description": 'A spilt bottle of Rage turned an innocent tree trunk into "The Log". Now, it seeks revenge by crushing anything in its path!',
        "id": 28000011,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/_iDwuDLexHPFZ_x4_a0eP-rxCS6vwWgTs6DLauwwoaY.png",
    },
    "Tornado": {
        "key": "tornado",
        "name": "Tornado",
        "elixir": 3,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 8,
        "description": "Drags enemy troops to its center while dealing damage over time, just like a magnet. A big, swirling, Tornado-y magnet. Doesn't affect buildings.",
        "id": 28000012,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/QJB-QK1QJHdw4hjpAwVSyZBozc2ZWAR9pQ-SMUyKaT0.png",
    },
    "Clone": {
        "key": "clone",
        "name": "Clone",
        "elixir": 3,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 11,
        "description": "Duplicates all friendly troops in the target area. Cloned troops are fragile, but pack the same punch as the original! Doesn't affect buildings.",
        "id": 28000013,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/mHVCet-1TkwWq-pxVIU2ZWY9_2z7Z7wtP25ArEUsP_g.png",
    },
    "Earthquake": {
        "name": "Earthquake",
        "elixir": 3,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/XeQXcrUu59C52DslyZVwCnbi4yamID-WxfVZLShgZmE.png",
    },
    "Barbarian Barrel": {
        "key": "barbarian-barrel",
        "name": "Barbarian Barrel",
        "elixir": 2,
        "type": "Spell",
        "rarity": "Epic",
        "arena": 3,
        "description": "It rolls over and damages anything in its path, then breaks open and out pops a Barbarian! How did he get inside?!",
        "id": 28000015,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/Gb0G1yNy0i5cIGUHin8uoFWxqntNtRPhY_jeMXg7HnA.png",
    },
    "Heal Spirit": {
        "name": "Heal Spirit",
        "elixir": 1,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/GITl06sa2nGRLPvboyXbGEv5E3I-wAwn1Eqa5esggbc.png",
    },
    "Giant Snowball": {
        "key": "giant-snowball",
        "name": "Giant Snowball",
        "elixir": 2,
        "type": "Spell",
        "rarity": "Common",
        "arena": 8,
        "description": "It's HUGE! Once it began rolling down Frozen Peak, there was no stopping it. Enemies hit are knocked back and slowed down.",
        "id": 28000017,
        "imageURL": "https://api-assets.clashroyale.com/cards/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png",
    },
    "Royal Delivery": {
        "name": "Royal Delivery",
        "elixir": 7,
        "alert": "NO INFO FROM ROAYLE API",
        "imageURL": "https://api-assets.clashroyale.com/cards/300/LPg7AGjGI3_xmi7gLLgGC50yKM1jJ2teWkZfoHJcIZo.png",
    },
}
